# Modified NFL Prop Agent Config (Week 3 based)
odds_api_key: "${ODDS_API_KEY}"
sport_key: "americanfootball_nfl"
regions: "us"
odds_format: "american"

# Target books remain the same as the original config; adjust as needed
target_books:
  - fanduel
  - espnbet
  - betmgm
  - caesars
  - fanatics
  - ballybet

# Restrict to the six core markets – yards and touchdowns for passing, rushing and receiving
markets:
  - player_pass_yds
  - player_pass_tds
  - player_rush_yds
  - player_rush_tds
  - player_reception_yds
  - player_reception_tds

# Odds levels for EV snapshots (unchanged)
odds_levels: [-120, -110, 100]

# Variance blending coefficient
blend_alpha: 0.35

# Outcome sigma defaults – updated using Week 3 stats
outcome_sigma:
  QB:
    player_pass_yds: 33.0
    player_pass_tds: 0.36
    player_rush_yds: 4.6
    player_rush_tds: 0.07
  RB:
    player_rush_yds: 4.5
    player_rush_tds: 0.03
    player_reception_yds: 1.8
    player_reception_tds: 0.01
  TE:
    player_rush_yds: 0.02
    player_rush_tds: 0.001
    player_reception_yds: 6.7
    player_reception_tds: 0.06
  WR:
    player_rush_yds: 0.94
    player_rush_tds: 0.01
    player_reception_yds: 9.1
    player_reception_tds: 0.08

# Bankroll and staking parameters (unchanged)
bankroll: 1000.0
unit_pct: 0.01
ev_bands:
  - {min_ev: 0.08, stake_u: 1.0}
  - {min_ev: 0.04, stake_u: 0.5}
  - {min_ev: 0.02, stake_u: 0.3}

# Juice threshold raised to allow lines as high as –140
max_juice: -140

# Return top 25 edges by default
top_n: 25
