# Modified NFL Prop Agent Config (Updated for Massachusetts & Extended Markets)

# Use multiple regions to ensure coverage of US and US2 bookmakers. Adding
# `us2` allows bookmakers like ESPN Bet and Bally Bet to appear in odds. See
# the Odds API documentation for region codes【150563287621877†L44-L69】.
regions: "us,us2"

odds_api_key: "${ODDS_API_KEY}"

sport_key: "americanfootball_nfl"

odds_format: "american"

# Target bookmakers limited to operators licensed in Massachusetts. According
# to the Massachusetts Gaming Commission, the Commonwealth currently has seven
# online sports wagering licensees: BetMGM, Caesars Sportsbook (William Hill
# US), Fanatics Betting & Gaming, Penn Sports Interactive (ESPN Bet), Bally
# Bet, DraftKings and FanDuel【997424387851567†L147-L167】. The keys here
# correspond to the bookmaker identifiers used by The Odds API【150563287621877†L44-L69】.
target_books:
  - fanduel
  - draftkings
  - betmgm
  - williamhill_us  # Caesars Sportsbook
  - espnbet          # Penn Sports Interactive/ESPN Bet
  - fanatics
  - ballybet

# Markets to request from The Odds API.
#
# We focus on the six core markets for NFL player props: passing yards,
# passing touchdowns, rushing yards, rushing touchdowns, receiving yards
# and receiving touchdowns.  Additional markets like receptions or
# pass+rush yards can be added in future but are excluded here per
# the current configuration.
markets:
  - player_pass_yds
  - player_pass_tds
  - player_rush_yds
  - player_rush_tds
  - player_reception_yds
  - player_reception_tds

# Odds levels for EV snapshots (unchanged)
odds_levels: [-120, -110, 100]

# Variance blending coefficient
blend_alpha: 0.35

# Outcome sigma defaults (updated to include new markets). These values are
# rough estimates; adjust based on your projection data if more accurate
# standard deviations are available.
outcome_sigma:
  QB:
    player_pass_yds: 33.0
    player_pass_tds: 0.36
    player_rush_yds: 4.6
    player_rush_tds: 0.07
  RB:
    player_rush_yds: 4.5
    player_rush_tds: 0.03
    player_reception_yds: 1.8
    player_reception_tds: 0.01
  TE:
    player_rush_yds: 0.02
    player_rush_tds: 0.001
    player_reception_yds: 6.7
    player_reception_tds: 0.06
  WR:
    player_rush_yds: 0.94
    player_rush_tds: 0.01
    player_reception_yds: 9.1
    player_reception_tds: 0.08

# Bankroll and staking parameters (unchanged)
bankroll: 1000.0
unit_pct: 0.01
ev_bands:
  - {min_ev: 0.08, stake_u: 1.0}
  - {min_ev: 0.04, stake_u: 0.5}
  - {min_ev: 0.02, stake_u: 0.3}

# Juice threshold raised to allow lines as high as –140
max_juice: -140

# Return top 25 edges by default
top_n: 25
