name: FFA Raw Stats Fetch

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "Run mode (start with smoke)"
        required: true
        default: "smoke"
        type: choice
        options: [smoke, real]
      debug:
        description: "Enable debug logs"
        required: false
        default: "0"
        type: choice
        options: ["0","1"]

permissions:
  contents: read

concurrency:
  group: ffa-raw-stats-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify R script exists
        run: |
          test -f scripts/ffa_fetch.R || { echo "::error::Missing scripts/ffa_fetch.R"; ls -R; exit 1; }

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.3'

      - name: System libs for httr2/rvest/xml2
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libxml2-dev libssl-dev

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("httr2","rvest","readr","dplyr","stringr"), repos="https://cloud.r-project.org")'

      - name: Smoke test (no secrets, no site)
        if: ${{ github.event.inputs.mode == 'smoke' }}
        run: |
          Rscript scripts/ffa_fetch.R --smoke-test=true --out=artifacts/ffa_smoke.csv
          echo "== Smoke output =="
          head -n 5 artifacts/ffa_smoke.csv || true
          ls -lh artifacts || true

      - name: Real fetch (cookie + direct CSV URL)
        if: ${{ github.event.inputs.mode == 'real' }}
        env:
          FFA_COOKIE: ${{ secrets.FFA_COOKIE }}
          FFA_RAW_STATS_URL: ${{ secrets.FFA_RAW_STATS_URL }}
          FFA_DEBUG: ${{ github.event.inputs.debug }}
        run: |
          mkdir -p artifacts
          if [ -z "${FFA_COOKIE}" ] || [ -z "${FFA_RAW_STATS_URL}" ]; then
            echo "::error::Secrets FFA_COOKIE and FFA_RAW_STATS_URL are required for real mode."
            exit 1
          fi
          Rscript scripts/ffa_fetch.R --smoke-test=false --out=artifacts/ffa_raw_stats.csv
          echo "== Real output preview =="
          head -n 5 artifacts/ffa_raw_stats.csv || true
          ls -lh artifacts || true

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ffa-output
          path: artifacts/
