name: FFA: Shiny CSV Fetch

on:
  workflow_dispatch: {}
  push:
    paths:
      - ".github/workflows/ffa_shiny.yml"
      - "scripts/ffa_shiny_download.R"

jobs:
  shiny_fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("chromote","fs","jsonlite"), repos="https://cloud.r-project.org")'

      - name: Download CSV from Shiny
        env:
          FFA_SHINY_URL: https://ffashiny.shinyapps.io/newApp/
          FFA_DOWNLOAD_SELECTOR: a#projections_page-proj-download_projections-download
          FFA_DOWNLOAD_TIMEOUT: "90"
          FFA_OUT: artifacts/ffa_raw_stats.csv
        run: Rscript scripts/ffa_shiny_download.R

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffa-output
          path: artifacts/*.csv
