name: "Prop Agent: scan & alert"

on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/30 * * * *"  # every 30 minutes; adjust as you like

permissions:
  contents: read

jobs:
  run_agent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install "pandas<3.0" numpy requests pyyaml

      # If your projections file is produced by another job/artifact, fetch it here.
      # Otherwise ensure the CSV lives at data/projections.csv or set PROJECTIONS_CSV below.

      - name: Run agent
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
          PROJECTIONS_PATH: ${{ inputs.projections_path }} # may be empty to auto-pick
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}  # optional, for alerts.py
          ENABLE_ALERTS: "1"        # set "0" to disable alerts
          ALERT_MIN_EV: "0.06"      # 6% EV threshold
          EDGES_OUT: artifacts/edges_bestbook.csv
          EDGES_JSON_OUT: artifacts/edges_bestbook.json
          PROJECTIONS_CSV: data/projections.csv   # change if your CSV lives elsewhere
          PROFILE: base
          DAYS_FROM: "7"
          MAX_CALLS: "1000"
          TOP_PRINT: "15"
          LOG_MARKETS_ONCE: "1"     # <-- enables debug log for markets
        run: |
          mkdir -p artifacts
          python -u agent_cli.py --projections "$PROJECTIONS_CSV" --profile "$PROFILE" 2>&1 | tee artifacts/agent_run.log

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: prop-agent-output
          path: artifacts/*
          if-no-files-found: error
