name: NFL Prop Agent (Scheduled)

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 13 * * 2-6'   # 09:00 ET Tue–Sat (13:00 UTC)
    - cron: '30 23 * * 4'    # Thu 19:30 ET
    - cron: '30 16 * * 0'    # Sun 12:30 ET
    - cron: '30 23 * * 1'    # Mon 19:30 ET

jobs:
  run-agent:
    runs-on: ubuntu-latest
    env:
      ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
      GOOGLE_CLOUD_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
      GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/sa.json

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Materialize Firestore service account (optional)
        env:
          FIREBASE_SA_JSON: ${{ secrets.FIREBASE_SA_JSON }}
        run: |
          if [ -n "$FIREBASE_SA_JSON" ]; then
            echo "$FIREBASE_SA_JSON" > sa.json
            echo "Service account JSON written to sa.json"
          else
            echo "No FIREBASE_SA_JSON secret set; skipping Firestore auth file."
          fi

      - name: Run agent (base profile)
        run: |
          python agent_cli.py --projections data/raw_stats_current.csv --out edges_bestbook.csv --profile base --days 7 --max-calls 2000

      - name: Upload edges CSV
        uses: actions/upload-artifact@v4
        with:
          name: edges_bestbook
          path: edges_bestbook.csv

      - name: Upload API call log
        uses: actions/upload-artifact@v4
        with:
          name: odds_api_calls
          path: odds_api_calls.csv
          if-no-files-found: ignore

      # Optional Firestore push
      # - name: Push to Firestore
      #   if: ${{ env.GOOGLE_CLOUD_PROJECT != '' && hashFiles('sa.json') != '' }}
      #   run: |
      #     PYDATE=$(date -u +'%Y_%m_%d')
      #     python firestore_push.py --csv edges_bestbook.csv --collection "nfl_props/${PYDATE}/edges"
