name: NFL Prop Agent (Scheduled)

on:
  workflow_dispatch: {}
  schedule:
    # 09:00 AM ET Tue–Sat (13:00 UTC)
    - cron: '0 13 * * 2-6'
    # Pre-kickoff sweeps (Thu 7:30 PM ET, Sun 12:30 PM ET, Mon 7:30 PM ET)
    - cron: '30 23 * * 4'
    - cron: '30 16 * * 0'
    - cron: '30 23 * * 1'

jobs:
  run-agent:
    runs-on: ubuntu-latest
    env:
      # REQUIRED
      ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
      # OPTIONAL (only for Firestore push)
      GOOGLE_CLOUD_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
      GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/sa.json

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------------- R: install + fetch projections ----------------
      - name: Install system libraries for R
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev build-essential libgit2-dev

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.3'

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("remotes","dplyr","readr","stringr"), repos="https://cloud.r-project.org")'
          Rscript -e 'remotes::install_github("FantasyFootballAnalytics/ffanalytics")'

      - name: Fetch weekly projections (FFA)
        run: Rscript R/fetch_projections.R

      - name: Upload FFA projections (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: projections_ffa_week
          path: data/projections_ffa_week.csv

      # ---------------- Python: agent run ----------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Materialize Firestore service account (optional)
        env:
          FIREBASE_SA_JSON: ${{ secrets.FIREBASE_SA_JSON }}
        run: |
          if [ -n "$FIREBASE_SA_JSON" ]; then
            echo "$FIREBASE_SA_JSON" > sa.json
            echo "Service account JSON written to sa.json"
          else
            echo "No FIREBASE_SA_JSON secret set; skipping Firestore auth file."
          fi

      - name: Run agent (base profile)
        run: |
          # Adjust --profile heavy and --max-calls if you want to use more of your 20k quota
          python agent_cli.py --projections data/projections_ffa_week.csv --out edges_bestbook.csv --profile base --days 7 --max-calls 5000

      - name: Upload edges CSV
        uses: actions/upload-artifact@v4
        with:
          name: edges_bestbook
          path: edges_bestbook.csv

      - name: Upload API call log
        uses: actions/upload-artifact@v4
        with:
          name: odds_api_calls
          path: odds_api_calls.csv
          if-no-files-found: ignore

      # ---------------- Optional: push results to Firestore ----------------
      # - name: Push to Firestore
      #   if: ${{ env.GOOGLE_CLOUD_PROJECT != '' && hashFiles('sa.json') != '' }}
      #   run: |
      #     PYDATE=$(date -u +'%Y_%m_%d')
      #     python firestore_push.py --csv edges_bestbook.csv --collection "nfl_props/${PYDATE}/edges"
